[package]
name = "cargo-compare"
version = "0.1.0"
authors = ["Rain <rain1@fb.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.43"
cargo = "0.55.0"
diffus = "0.10.0"
either = "1.6.1"
itertools = "0.10.1"
guppy = { path = "../../guppy" }
guppy-cmdlib = { path = "../../guppy-cmdlib", features = ["proptest1"] }
structopt = "0.3.23"
tempfile = "3.2.0"
once_cell = "1.8.0"
proptest = "1.0.0"
