# adapted from https://github.com/taiki-e/cargo-hack/blob/main/.github/workflows/release.yml

name: Publish releases to GitHub
on:
  push:
    tags:
      - '*'

jobs:
  target-spec-release:
    if: github.repository_owner == 'facebookincubator' && startsWith(github.ref_name, 'target-spec-')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/create-gh-release-action@v1
        with:
          prefix: target-spec
          changelog: target-spec/CHANGELOG.md
          title: $prefix $version
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  guppy-summaries-release:
    if: github.repository_owner == 'facebookincubator' && startsWith(github.ref_name, 'guppy-summaries-')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/create-gh-release-action@v1
        with:
          prefix: guppy-summaries
          changelog: guppy-summaries/CHANGELOG.md
          title: $prefix $version
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  guppy-release:
    # There's no regex filtering in if conditionals, so we need to use the first component of the version number.
    if: github.repository_owner == 'facebookincubator' && startsWith(github.ref_name, 'guppy-0')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/create-gh-release-action@v1
        with:
          prefix: guppy
          changelog: guppy/CHANGELOG.md
          title: $prefix $version
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  determinator-release:
    if: github.repository_owner == 'facebookincubator' && startsWith(github.ref_name, 'determinator-')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/create-gh-release-action@v1
        with:
          prefix: determinator
          changelog: tools/determinator/CHANGELOG.md
          title: $prefix $version
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  hakari-release:
    if: github.repository_owner == 'facebookincubator' && startsWith(github.ref_name, 'hakari-')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/create-gh-release-action@v1
        with:
          prefix: hakari
          changelog: tools/hakari/CHANGELOG.md
          title: $prefix $version
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cargo-hakari-release:
    if: github.repository_owner == 'facebookincubator' && startsWith(github.ref_name, 'cargo-hakari-')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/create-gh-release-action@v1
        with:
          prefix: cargo-hakari
          changelog: tools/cargo-hakari/CHANGELOG.md
          title: $prefix $version
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
